language: node_js
node_js:
- lts/*
install:
- npm install
script:
- npm run build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  keep_history: true
  github_token: "${gh-token}"
  on:
    branch: master